### ISSUE TITLE
release 1.0.0 missing sqlite dependency?

### ISSUE THREAD

**Issue by RussellGrew** [geoadmin/service-bdms#13]
Thanks for sharing such a great project. I have been able to build and run successfully in the past. I wonder if there is a missing dependency in the latest version. Details below

```
 * Starting nginx nginx
   ...done.
 * Starting PostgreSQL 10 database server
   ...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/spatialite/connection.py", line 95, in enable_spatialite_extension
    self.execute("SELECT load_extension('%s')" % ext_name)
sqlite3.OperationalError: mod_spatialite.dylib: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bms/main.py", line 29, in <module>
    from bms import (
  File "./bms/__init__.py", line 20, in <module>
    from bms.v1.borehole.producer import BoreholeProducerHandler
  File "./bms/v1/borehole/producer.py", line 30, in <module>
    from bms.v1.setting import (
  File "./bms/v1/setting/__init__.py", line 3, in <module>
    from bms.v1.setting.download import DownloadHandler
  File "./bms/v1/setting/download.py", line 3, in <module>
    from bms.v1.borehole.export import (
  File "./bms/v1/borehole/export/__init__.py", line 8, in <module>
    from bms.v1.borehole.export.spatialite import ExportSpatiaLite
  File "./bms/v1/borehole/export/spatialite.py", line 6, in <module>
    import spatialite
  File "/usr/local/lib/python3.7/dist-packages/spatialite/__init__.py", line 12, in <module>
    spatialite_version = get_spatialite_version()
  File "/usr/local/lib/python3.7/dist-packages/spatialite/connection.py", line 124, in get_spatialite_version
    with connect(':memory:') as db:
  File "/usr/local/lib/python3.7/dist-packages/spatialite/connection.py", line 120, in connect
    return sqlite3.connect(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/spatialite/connection.py", line 79, in __init__
    self.enable_spatialite_extension()
  File "/usr/local/lib/python3.7/dist-packages/spatialite/connection.py", line 106, in enable_spatialite_extension
    raise LoadExtensionError(msg) from error
spatialite.connection.LoadExtensionError: Failed to load SpatiaLite extension. Verify that your python module sqlite3 has load_extension support and check that libspatialite is installed. Tried extension names: mod_spatialite, mod_spatialite.so, mod_spatialite.dylib
Failed to start my_third_process: 1
```

Any advice is appreciated. I am hoping to help you find possible bugs rather than criticise.

**Comment by mantonovic** [comment]
Hi @RussellGrew ,
Are you using the [Dockerfile](https://github.com/geoadmin/service-bdms/blob/v1.0.0/config/Dockerfile) in the ./config directory?
If yes, try to add the missing package in the docker file:

```
RUN apt-get -y update &&\
    apt-get -y install unzip &&\
    apt-get -y install python3.7 &&\
    apt-get -y install python3-pip &&\
    apt-get -y install nginx &&\
    apt-get -y install nano &&\
    apt-get -y install npm &&\
    apt-get -y install git &&\
    DEBIAN_FRONTEND=noninteractive apt-get -y install postgresql postgresql-contrib &&\
    apt-get -y install postgis
    **apt-get -y install  libsqlite3-mod-spatialite** 
```

And try again..

**Comment by RussellGrew** [comment]
That did it.

Many thanks!

I hope to soon find time to better understand the build process. 

Presently with the "as cloned" deployment the borehole map is blank unless I am using the PC which is hosting Swisstopo. I always see "white background" and not "colour map" or "grey map". Is there some simple config I can edit for this? Or I did wonder if CORS is somehow involved.

I am trying to host bdms as a demonstration for my colleagues.

**Comment by mantonovic** [comment]
Currently the maps used in BDMS came from Swisstopo WMTS server [1] and you need to register your domain to make it work.
But if you access your BDMS instance using as address localhost (or 127.0.0.1) it will works [2], this is intended for development purpose only.

Eventually you can try from the settings menu add an external WMS to add a custom background.

[1] https://shop.swisstopo.admin.ch/en/products/geoservice/swisstopo_geoservices 
[2] https://api3.geo.admin.ch/api/faq/index.html#can-i-use-http-localhost-to-test-my-developments

**Comment by RussellGrew** [comment]
Good to know. 

Thanks for your help.
