### ISSUE TITLE
docker container wont run

### ISSUE THREAD

**Issue by RussellGrew** [geoadmin/service-bdms#8]
I was very interested to see your talk abstract at FOSS4G 2019. I am not attending but look forward to watching the talk on youtube.

Following a 

`docker pull swisstopo/service-bdms`

and then my attempts to run it

`docker run -d --name bdmsContainer -p 80:80 swisstopo/service-bdms`

it quickly falls over. 

```
Traceback (most recent call last):
  File "bms/main.py", line 107, in <module>
    application.pool = ioloop.run_until_complete(get_conn())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "bms/main.py", line 23, in get_conn
    database=options.pg_database, host=options.pg_host, port=options.pg_port)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 400, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 417, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 463, in _get_new_connection
    **self._connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 551, in _connect
    raise last_error
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 513, in _connect_addr
    connector, timeout=timeout, loop=loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 963, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 5432), [Errno 99] Cannot assign requested address
```

I note the docker image has over 10k downloads so I think people must have it working.

I am assuming I can run the docker service-bdms and web-bdms runs external to this. 

I have tried this on Ubuntu 16.04 at home and also Win 10 at work. 

Any advice would be great.

**Comment by RussellGrew** [comment]
I decided to try building it myself. 

It works great! Thanks for sharing such a detailed software package.

I was confused in that I thought I would also have to run the web page and java library. I see now that this service includes these components.
